### ISSUE TITLE
"colcon-terminal-notifier.app does not exist" error on OS X

### ISSUE THREAD

**Issue by dhood** [colcon/colcon-notification#17]
At the end of builds on OS X I get the following:

```
$ colcon build --symlink-install --cmake-args -DBUILD_TESTING=OFF --packages-select ros1_bridge
Starting >>> ros1_bridge
Finished <<< ros1_bridge [3.16s]

Summary: 1 package finished [5.39s]
The file /usr/local/share/colcon-notification/colcon-terminal-notifier.app does not exist.
```

I have `colcon-notification-0.2.2` installed into `/usr/local/lib/python3.6/site-packages/colcon_notification`.

This isn't a high priority issue I imagine.

**Comment by dirk-thomas** [comment]
`<prefix>/share/colcon-notification/colcon-terminal-notifier.app` is certainly the location it is supposed to be installed into (see [setup.py](https://github.com/colcon/colcon-notification/blob/8c424a9e4987a0d871b9728b4676c8d1b4d2b232/setup.py#L16). The Debian package shows the files in the intended location. So something seems to be different in your case.

@dhood What version of setuptools are you having installed (`pip3 freeze --all`)?

@Karsten1987 @wjwwood Can either of you try this on macOS and report what behavior / location they are seeing?

**Comment by dhood** [comment]
`setuptools==39.2.0` (up-to-date)

**Comment by wjwwood** [comment]
I see the same thing, but I usually run with `desktop_notification-` so I didn't notice it. It used to do something I thought. I've since updated colcon several times.

```
% python3 -m pip freeze --all | grep setuptools
setuptools==39.2.0
```
