### ISSUE TITLE
Error after build on macOS when desktop notification handler is enabled

### ISSUE THREAD

**Issue by jacobperron** [colcon/colcon-notification#32]
State:
* macOS High Sierra
* colcon-notification version: 0.2.7

Steps to reproduce:

```bash
mkdir -p foo_ws/src
cd foo_ws
colcon build
```

After the build succeeds we see the error:

```
The file /Users/jacob/foo_ws/None does not exist.
```

If we disable the desktop notification event handler the error does not happen:

```
colcon build --event-handler desktop_notification-
```

**Comment by dirk-thomas** [comment]
The path of the terminal notifier app isn't found: https://github.com/colcon/colcon-notification/blob/146aca75a4d6fcac2d139bc1367375a4fa06dcf8/colcon_notification/desktop_notification/terminal_notifier.py#L92-L93

1. A fix to actually find and use the terminal notifier app
2. Add an additional check if it wasn't found to skip running the command.
