### ISSUE TITLE
How do I disable output colors?

### ISSUE THREAD

**Issue by realtime-neil** [colcon/colcon-notification#50]
I'm not sure if this is a question for this repo or that of `colcon-core`. I can't seem to find any command line options that mention "color" and `export NO_COLOR=1` has no effect.

**Comment by jacobperron** [comment]
Are you referring to the logger output? If so, I believe this is configured in colcon-core.

Here we can see the package `coloredlogs` is used:

https://github.com/colcon/colcon-core/blob/83094da173d80559c92487fd1caca0a249e85b11/colcon_core/logging.py#L17

And according to the [`colordlogs` docs](https://coloredlogs.readthedocs.io/en/latest/api.html#environment-variables) it should respect the environment variable `NO_COLOR`.

I've done a simple test with a build that contains warnings and setting the environment variable works; no color is output:

    NO_COLOR=1 colcon build

I'm not sure why you are seeing color. Maybe logging is happening on a tty-like device (ie. `os.isatty()` is `True`)? You could try uninstalling `coloredlogs`. I'm going to close this ticket, but feel free to continue commenting. If you have a reproducible example of a bug, please open a ticket on colcon-core.
