### ISSUE TITLE
Incompatible release 0.2.15 for Debian 10/11

### ISSUE THREAD

**Issue by nlimpert** [colcon/colcon-notification#63]
Version tag `0.2.15` released for Debian 10/11 doesn't seem to be installable due to `zstd` missing.

This is a follow-up of https://github.com/colcon/colcon-defaults/issues/36#issuecomment-1400283151 .

If I had seen the related change in `colcon-defaults` I'd submit a PR for `colcon-notification` accordingly.

**Comment by nlimpert** [comment]
@cottsay friendly ping

This seems to be the case since https://github.com/colcon/colcon-notification/commit/8ae243584c7efd8d2912057d3911a6e156afcece .

When I revert this particular commit I can build the package in Debian 11 (via `python3 setup.py --command-packages=stdeb.command bdist_deb`) which installs fine.

Debian 11 ships `python3-setuptools` version `52.0.0` per default so removing the dependency in `stdeb.cfg` doesn't help.

I believe that's one regression as noted in https://github.com/colcon/colcon-notification/pull/61#pullrequestreview-1188934149

**Comment by nlimpert** [comment]
@nuclearsandwich friendly ping.
I'm not sure how to fix this properly - the naive approach might be to simply depend on `dpkg (>= 1.21.18)` but I'm not sure whether that prevents the deployment of the package on the debian package repository:

```diff
diff --git a/stdeb.cfg b/stdeb.cfg
index 71e6380..861a4fb 100644
--- a/stdeb.cfg
+++ b/stdeb.cfg
@@ -1,7 +1,7 @@
 [colcon-notification]
 No-Python2:
 Build-Depends: python3-setuptools (>= 53.1.0)
-Depends3: python3-colcon-core (>= 0.3.7), python3-notify2
+Depends3: python3-colcon-core (>= 0.3.7), python3-notify2, dpkg (>=1.21.18)
 Suite: bionic focal jammy stretch buster bullseye
 X-Python3-Version: >= 3.5
 Setup-Env-Vars: BUILD_DEBIAN_PACKAGE=1
```
This at least prevents installation of the package on Debian 11 (as expected).

Please let me know if there's a proper way to fix this - or if you believe the above suffices I'm happy to provide a PR.

**Comment by christophfroehlich** [comment]
+1 also struggled today to install colcon on Debian 11

**Comment by russkel** [comment]
+1 the struggle is real

**Comment by KyleJewiss** [comment]
For those struggling, this method of repacking worked for me. From this thread: https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg

```
# Extract files from the archive
ar x some-package.deb
# Uncompress zstd files an re-compress them using xz
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
# Re-create the Debian package in /tmp/
ar -m -c -a sdsd /tmp/some-package.deb debian-binary control.tar.xz data.tar.xz
# Clean up (optional)
rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst
```

**Comment by christophfroehlich** [comment]
> For those struggling, this method of repacking worked for me. From this thread: https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg
> 
> ```
> # Extract files from the archive
> ar x some-package.deb
> # Uncompress zstd files an re-compress them using xz
> zstd -d < control.tar.zst | xz > control.tar.xz
> zstd -d < data.tar.zst | xz > data.tar.xz
> # Re-create the Debian package in /tmp/
> ar -m -c -a sdsd /tmp/some-package.deb debian-binary control.tar.xz data.tar.xz
> # Clean up (optional)
> rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst
> ```

That works for me too, but is pain to integrate such a hack in a CI build.
